export const products = [
  {id:'hario-v60', name:'Hario V60 Dripper 02', brand:'Hario', category:'Coffee', price:12, sku:'HAR-V60-02', stock:'In stock', image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=85', description:'A ceramic pour-over dripper from Hario, designed for everyday manual coffee brewing.', details:['Ceramic dripper','Size 02','Paper filters required'], source:'Product information is based on manufacturer-published details.'},
  {id:'fellow-carter', name:'Fellow Carter Move Mug', brand:'Fellow', category:'Coffee', price:35, sku:'FEL-CAR-MOVE', stock:'In stock', image:'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=1200&q=85', description:'Fellow’s travel coffee mug with a slim profile made for a daily commute or a long walk.', details:['Travel mug','Ceramic interior coating','Leak-resistant lid'], source:'Finish and availability may vary by market.'},
  {id:'moleskine-classic', name:'Moleskine Classic Notebook', brand:'Moleskine', category:'Writing', price:25, sku:'MOL-CLSC-LG', stock:'In stock', image:'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85', description:'The classic hardcover notebook from Moleskine, made for notes, lists, sketches and ideas.', details:['Hard cover','Elastic closure','Bookmark ribbon'], source:'Paper format and ruling are selected at checkout when available.'},
  {id:'leuchtturm-1917', name:'LEUCHTTURM1917 Medium A5', brand:'LEUCHTTURM1917', category:'Writing', price:24, sku:'LEU-A5-MED', stock:'Low stock', image:'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=1200&q=85', description:'A numbered-page notebook from LEUCHTTURM1917 for planning, journaling and focused work.', details:['A5 format','Numbered pages','Two bookmarks'], source:'Colors are subject to regional availability.'},
  {id:'hario-skerton', name:'Hario Skerton Plus Grinder', brand:'Hario', category:'Coffee', price:47, sku:'HAR-SKT-PLUS', stock:'In stock', image:'https://images.unsplash.com/photo-1497636577773-f1231844b336?auto=format&fit=crop&w=1200&q=85', description:'A hand coffee grinder from Hario for freshly ground coffee at home or away.', details:['Manual grinder','Ceramic burrs','Adjustable grind'], source:'Use only as directed by the manufacturer.'},
  {id:'kinfolk-home', name:'The Kinfolk Home', brand:'Kinfolk', category:'Books', price:40, sku:'KNF-HOME-HC', stock:'In stock', image:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=1200&q=85', description:'A hardcover book from Kinfolk exploring interiors and the people who make them personal.', details:['Hardcover','Lifestyle & interiors','English edition'], source:'Edition availability may change.'}
];
export const categories = ['Coffee','Writing','Books'];
export const money = value => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
